<!doctype html>
<html>
	<head>
		<meta charset="UTF-8">
		<title> Trop Stroumpfette</title>
		<link rel="icon" href="favicon.ico" />
		<link rel="stylesheet" href="view/css/style.css" type="text/css" />

		<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
		<script src="view/js/script.js"></script>
	</head>
	<body>
		<header>
			<nav>
				<a href="index.php" data-href="home">Accueil</a>
				<a href="about" data-href="about">A propos</a>
				<a href="contact" data-href="contact">Contact</a>
				<a href="message" data-href="message">Messages</a>
			</nav>
		</header>
		<main>